### ISSUE TITLE
Documentation for production mode

### ISSUE THREAD

**Issue by talss89** [CitizensFoundation/your-priorities-app#18]
Thanks for sharing this great platform. 

We're having trouble understanding how the SSL configuration is set up in production mode. The readme implies that the app can be run without a webserver (using express). Is this only for the development environment? Should we be running, say, nginx, and then using the express app as the backend?

I'd be happy to contribute by writing some documentation around this if it would be useful. I found the current readme to be a little patchy.

All the best,

Tom.

**Comment by rbjarnason** [comment]
Hi Tom @talss89 

Thank you for you interest and Pull Requests for the Readme would be highly appreciated :) yes it is a bit patchy at the moment and can do with improvements.

We run our own production environments on Heroku but otherwise we recommend using Nginx or Apache and documentation for this is indeed missing. For Open Active Voting our budget voting solution we have created a Docker environment that uses Nginx. Ideally we'd like to have Your Priorities containers that can be used with for example Kubernetes. But as most of the development of Your Priorities is volunteer based and we ourselves use Heroku we've not found the time yet to do this.

**Comment by rbjarnason** [comment]
Here is recent documentation for Docker based installation: https://github.com/CitizensFoundation/your-priorities-app/tree/master/deployment
