### ISSUE TITLE
Anonymous login broken? | GDPR conformity 

### ISSUE THREAD

**Issue by andredaa** [CitizensFoundation/your-priorities-app#20]
Hello everyone!
Your priorities looks like a fantastic tool and we are strongly considering it for our mobility project "Cities4People". 
*Anonymous login*
1)I have an issue with the anonymous login though. As users have to login and provide their name and email address, I think the site would be required to have a GDPR statement (and at Signup a checkbox to agree to it) for use in Europe, right?
I cannot find a GDPR statement on the your priorities website though. 
I thought we could bypass the problem by marking our group as "automatic anonymous login" + "allow anonymous users" - however the page remains unaccessable without logging in. 

This is my anonymous test group: https://yrpri.org/group/1622

Am I doing something wrong - or is the anonymous login broken?

If it really is a bug, we could consider fixing it and make a pull request - would that be possible?

2) *GDPR conform signup*
I am not a specialist on the GDPR topic - however it seems to me that you would need a privacy declaration and a opt-in box where people agree to the use of their data and the receiving of emails.

We could even consider making a pull request for this.

Thank you for your help!
Andre

**Comment by rbjarnason** [comment]
Hello @andredaa!

Thanks for kind words and we're happy to help your exciting project to make it a success :)

Due to the global nature of yrpri.org we don't have a common GDRP policy for all communities but you can add your own using the Manage Pages feature - see more here on how to use it https://docs.google.com/document/d/1OVCkpcOa4GcUmw6iDPqckMzWIaGi5Wso6UGacrIfFpw/edit#heading=h.nbg8m0pa8u08 - then your GDPR policy is accessible at the top of the (?) icon at the top of the screen.

We have been planning to add a feature where you can connect Pages to a checkbox in the Signup Screen. We will put this on the highest priority to implement, start today and will launch it live in a couple of days. Then you will be 1) Create a GDPR statement using the Community Manage Pages feature (in multiple languages if needed) then 2) connect this statement to the signup screen using the Community Edit feature so people how to visit your community need to click to accept the statement.

Regarding anonymous login then a) Your group is now set to Open to Community and the Community is secret - this disables anonymous login. b) For auto login: You need to supply autoLogin=1 to the url like https://c4p-hamburg.yrpri.org/group/1622?autoLogin=1

ps. If you want to contact me on robert@citizens.is I'm also happy to meet with you guys on Skype and give some advice in terms of how then best to use the platform and how to get people using it.

**Comment by andredaa** [comment]
Hello Robin!
Wow!
Thanks for the fast and detailed answer. 
Fantastic news about the GDPR statement + new signup form. 

Thanks for the instructions on the auto login. 

Thank you for offering your contact, we might be in touch a bit further down the road.

Best 
Andre :)

**Comment by rbjarnason** [comment]
@andredaa - the GDPR signup terms pull request is ready and we'll merge it tomorrow do around of QA and then launch it on the live server tomorrow night. See here:  https://github.com/CitizensFoundation/your-priorities-app/pull/21

**Comment by andredaa** [comment]
Thank you!
It makes me so happy that you responded so fast. Great engagement you have! :)
