### ISSUE TITLE
Question about super adminsitrator role

### ISSUE THREAD

**Issue by MarceMMAD** [CitizensFoundation/your-priorities-app#3]
Greetings. I have a question about the app administration.
Is there some kind of super admin role with a dashboard or configuration page where someone can configure the app in more ways than the administrator of a community or a group? Or would it take code and database changes to do so?

**Comment by rbjarnason** [comment]
At first you are probably missing the domain level admin access.  You can active it by running the following command in the root of your app. This will give admin access to all domains, community and group on your development instance.

```bash
node server_api/scripts/setAdminOnAll.js your@email.com
```

Then you have access to the domain admin the same way as community and groups. Check it out and let me know anything specifically that you are missing.  In general all config options should be available through the domain, community, group and post level edit menus on the right side of the info box.

**Comment by rbjarnason** [comment]
I've also added this information to the readme.

**Comment by MarceMMAD** [comment]
Thank you very much @rbjarnason ! That is exactly what I needed! Now I can access the domains settings, but when I try to change any of them e.g., the domain description, nothing happengs when I press the UPDATE button.
No "executing UPDATE query" notification is shown in the shell.

**Comment by rbjarnason** [comment]
@MarceMMAD this is a problem because the APIs edit fields are empty and this is actually a bug in one of the Polymer web components - crashes on undefined state of paper-input when trying to send the PUT request. There is a PR here that fixes the issue, going to wait with doing a workaround hoping this will be merged soon into the master of this component: https://github.com/PolymerElements/iron-ajax/pull/234

A quick workaround is to add some random text into those API fields - do an update, then edit domain again and remove all the random text and leave just empty spaces.

**Comment by MarceMMAD** [comment]
Thanks a lot for the quick workaround and the explanation @rbjarnason.

**Comment by rbjarnason** [comment]
I've made a fork of iron-ajax and fixed the problem here: https://github.com/rbjarnason/iron-ajax/commit/e449ea318b7c39fdafec7158a79f7d72cb351f09
